config/routes.rb
Rails.application.routes.draw do

  root 'landing_pages#index'

  resources :shortened_urls do 
    collection do
      get :top_listings
    end
  end

  get "/:unique_key" => 'shortened_urls#convert', :as => :convert_link

  get "/your_short_url/:id" => 'shortened_urls#your_short_url', :as => :short_url

  
end

app/models/shortened_url.rb
class ShortenedUrl < ActiveRecord::Base
	default_scope { ShortenedUrl.order(use_count: :desc).limit(100) }
  after_create :generate
  # model is dealing with the generation of a url
  
  # make your own alphabet It contains 62 letters.
  @@chars = [*'0'..'9', *'a'..'z', *'A'..'Z', "_", "-"]

  # generae random links
  def generate
    #take an auto-generated, unique numerical key
    id = self.id

    #generate unique link using bijective_function function
    unique_key = bijective_function(id)
    
    #update unique key
    self.update_attributes!(unique_key: unique_key)
  end

private
  #requires use of integer division and modulo
  
  def bijective_function(id)
    return @@chars[0] if id == 0
    string = ""
    base = @@chars.length
    while id > 0
      string << @@chars[id.modulo(base)]
      id /= base
    end
    string.reverse
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
end

app/controllers/shortened_urls_controller.rb
class ShortenedUrlsController < ApplicationController
	def create
		shortUrl = ShortenedUrl.new(url_params)
		if shortUrl.save
			redirect_to  short_url_path(shortUrl.unique_key)
		end
	end

	def your_short_url	
		@uniqKey = ShortenedUrl.find_by_unique_key(params[:id])
		if @uniqKey.blank?
			redirect_to root_url
		end
	end

	def convert
		@uniqKey = ShortenedUrl.find_by_unique_key(params[:unique_key])
		if @uniqKey.present?
			# increment the count of shortened url used 
			@uniqKey.increment!(:use_count)

			# 301 redirect to the destination url
			head :moved_permanently, :location => @uniqKey.url
		else
			# if we don't find the shortened url, redirect to the root
			head :moved_permanently, :location => root_url
		end
	end

	def top_listings
		@shortUrls = ShortenedUrl.all
	end

	private
	  def url_params
	    params.require(:shortened_url).permit(:url)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing_pages/index.html.erb
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>My site</h4>
      <!-- <div class="col-md-12"> -->
        <h4><a class="btn btn-default" href="<%= top_listings_shortened_urls_path %>"><i class="glyphicon"></i> 100 Top Accessed URLS</a></h4>
      <!-- </div> -->
    </div>

    <div class="col-sm-9">
      <hr>
      <h2>Welcome to ShortURL!</h2>
      
      <p> Please enter a URL in the text field below, we will create a shortened URL.</p>
      <br><br>
      <%= form_for ShortenedUrl.new do |f| %>
        <div align="center">
          <label>Enter a long URL to make short:</label>
          <div class="input-group">
            <div class="col-xs-12">
              <span class="input-group-btn">
                <%= f.text_field :url, class: 'form-control' %>
                <%= f.button "Make ShortURL", class: 'btn btn-default'%>
              </span>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TinyUrl</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shortened_urls/top_listings.html.erb
<div class="row">
  
</div>
<div class="container">

  <hr><a class="btn btn-default" href="<%= root_url %>"><i class="glyphicon"></i> Home</a>
  
  <h2>100 the most frequently accessed URLs</h2>
             
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Original URL</th>
        <th>Shortened URL</th>
        <th>User Count</th>
      </tr>
    </thead>
    <tbody>
      <% @shortUrls.each do |url|%>
        <tr>
          <td><%= url.url%></td>
          <td><%= "#{root_url}#{url.unique_key}"%></td>
          <td><%= url.use_count%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shortened_urls/your_short_url.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-12 lead">Unique Key<hr></div>
          </div>
          <div class="row">
			<div class="col-md-4 text-center">
        <img class="img-circle avatar avatar-original" style="-webkit-user-select:none; 
        display:block; margin:auto;" src="http://robohash.org/sitsequiquia.png?size=120x120">
      </div>
            <div class="col-md-8">
              <div class="row">
                <div class="col-md-12">
                  <h1 class="only-bottom-margin">Shortened URL was created!</h1>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <span class="text-muted">Your Shortened Url:   </span> <b><%= "#{root_url}#{@uniqKey.unique_key}"%></b><br>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <hr><a class="btn btn-default pull-right" href="<%= root_url %>"><i class="glyphicon"></i> New Shortned URL</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>